In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], columns=['cgpa', 'resume_score', 'package'])

In [7]:
df

   cgpa  resume_score  package
0     8             8        4
1     7             9        5
2     6            10        6
3     5            12        7

In [10]:
def init_params(layer_dim):
  np.random.seed(3)
  params = {}
  l = len(layer_dim)

  for i in range(1, l):
    params['W' + str(i)] = np.ones((layer_dim[i-1], layer_dim[i])) * 0.1
    params['b' + str(i)] = np.zeros((layer_dim[i], 1))
  return params;

In [17]:
init_params([2, 2, 1])['W1']

array([[0.1, 0.1],
       [0.1, 0.1]])

In [18]:
from re import A
def linear_forward(A_prev, W, b):
  z = np.dot(W.T, A_prev) + b
  return z;

In [59]:
def forward_pass(X, params):
  A = X
  L = len(params) // 2      # number of layers in neural network

  for l in range(1, L+1):
    A_prev = A
    W1 = params['W' + str(l)]
    b1 = params['b' + str(l)]
    # print('A' + str(l-1) + ":", A_prev)
    # print('W' + str(l) + ":", W1)
    # print('b' + str(l) + ":", b1)
    # print('--' * 20)

    A = linear_forward(A_prev, W1, b1)
    # print("A" + str(l) + ": ", A)
    # print("**" * 20)

  return A, A_prev

In [37]:
# for first student
X = df[['cgpa', 'resume_score']].values[0].reshape(2, 1)
y = df[['package']].values[0][0]

params = init_params([2, 2, 1])

In [38]:
params

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [39]:
y_pred, A1 = forward_pass(X, params)

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************

In [40]:
# loss calculation
(y - 0.32)**2

np.float64(13.5424)

In [41]:
def update_params(parameters, y, y_hat, A1, X, lr=0.001):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (lr * 2 * (y - y_hat) * A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (lr * 2 * (y - y_hat) * A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (lr * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (lr * 2 * (y - y_hat) * parameters['W2'][0][0] * X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (lr * 2 * (y - y_hat) * parameters['W2'][0][0] * X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (lr * 2 * (y - y_hat) * parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (lr * 2 * (y - y_hat) * parameters['W2'][1][0] * X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (lr * 2 * (y - y_hat) * parameters['W2'][1][0] * X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (lr * 2 * (y - y_hat) * parameters['W2'][1][0])

In [42]:
y_hat = y_pred[0][0]
y_hat

np.float64(0.32000000000000006)

In [43]:
update_params(params, y, y_hat, A1, X)

In [45]:
# updated params
params

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [48]:
# for second student
X = df[['cgpa', 'resume_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['package']].values[1][0]

y_hat,A1 = forward_pass(X,params)
y_hat = y_hat[0][0]

update_params(params,y,y_hat,A1,X)

params

A0: [[7]
 [9]]
W1: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1: [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1: [[1.70612461]
 [1.70612461]]
W2: [[0.111776]
 [0.111776]]
b2: [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [49]:
# for third student
X = df[['cgpa', 'resume_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['package']].values[2][0]

y_hat,A1 = forward_pass(X,params)
y_hat = y_hat[0][0]

update_params(params,y,y_hat,A1,X)

params

A0: [[ 6]
 [10]]
W1: [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1: [[0.0019667]
 [0.0019667]]
----------------------------------------
A1:  [[1.83539945]
 [1.87200826]]
****************************************
A1: [[1.83539945]
 [1.87200826]]
W2: [[0.12712927]
 [0.12712927]]
b2: [[0.13612818]]
----------------------------------------
A2:  [[0.6074482]]
****************************************

{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]),
 'b1': array([[0.00355129],
        [0.00355555]]),
 'W2': array([[0.14692424],
        [0.14731907]]),
 'b2': array([[0.15810417]])}

In [52]:
(y - 0.801)**2

np.float64(38.427600999999996)

In [51]:
# for fourth student
X = df[['cgpa', 'resume_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['package']].values[3][0]

y_hat,A1 = forward_pass(X,params)
y_hat = y_hat[0][0]

update_params(params,y,y_hat,A1,X)

params

A0: [[ 5]
 [12]]
W1: [[0.12409711 0.13272353]
 [0.12412266 0.13276611]]
b1: [[0.00355129]
 [0.00355555]]
----------------------------------------
A1:  [[2.11350869]
 [2.26036654]]
****************************************
A1: [[2.11350869]
 [2.26036654]]
W2: [[0.14692424]
 [0.14731907]]
b2: [[0.15810417]]
----------------------------------------
A2:  [[0.80162493]]
****************************************

{'W1': array([[0.13482804, 0.15847776],
        [0.1349909 , 0.15884991]]),
 'b1': array([[0.00569748],
        [0.0057292 ]]),
 'W2': array([[0.17312488],
        [0.17534027]]),
 'b2': array([[0.18773702]])}

In [60]:
# epochs implementation from beginning

parameters = init_params([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'resume_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['package']].values[j][0]

    # Parameter initialization
    y_hat,A1 = forward_pass(X, parameters)
    y_hat = y_hat[0][0]

    update_params(parameters, y , y_hat, A1, X)

    Loss.append((y - y_hat)**2)


  print('Epoch - ', i+1, 'Loss - ', np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729625
Epoch -  4 Loss -  3.252093863403161
Epoch -  5 Loss -  1.3407132589299964

{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

In [56]:
Loss

[np.float64(0.5629279313986902),
 np.float64(0.1580422250418376),
 np.float64(1.6918971818989725),
 np.float64(2.949985697380485)]

## using keras to compare

In [75]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [62]:
df

   cgpa  resume_score  package
0     8             8        4
1     7             9        5
2     6            10        6
3     5            12        7

In [63]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [64]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [67]:
model.get_weights()

[array([[ 1.1756951 , -0.47754467],
        [-1.1494724 ,  0.7322066 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.8340882],
        [-0.9773102]], dtype=float32),
 array([0.], dtype=float32)]

In [71]:
model.set_weights([
    np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
    np.array([0., 0.], dtype=np.float32),
    np.array([[0.1], [0.1]], dtype=np.float32),
    np.array([0.], dtype=np.float32)
])

In [73]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [80]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [81]:

model.fit(
    df[['cgpa', 'resume_score']].values,
    df[['package']].values,
    epochs=75,
    verbose=1,
    batch_size=1
)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 1.0497
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0354
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0335
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0211
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0177
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0181
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0205
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0106
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0052
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0035
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9993
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.9987
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0002
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9976
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9896
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9885
Epoch 17/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9870
Epoch 18/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9831
Epoch 19/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9833
Epoch 20/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9791
Epoch 21/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9761
Epoch 22/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9746
Epoch 23/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9707
Epoch 24/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9686
Epoch 25/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9724
Epoch 26/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9643
Epoch 27/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9657
Epoch 28/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9610
Epoch 29/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9568
Epoch 30/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9549
Epoch 31/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9535
Epoch 32/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9538
Epoch 33/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9543
Epoch 34/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9453
Epoch 35/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9444
Epoch 36/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9443
Epoch 37/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9387
Epoch 38/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9357
Epoch 39/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9361
Epoch 40/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9302
Epoch 41/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9342
Epoch 42/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9318
Epoch 43/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9238
Epoch 44/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9225
Epoch 45/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9260
Epoch 46/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9190
Epoch 47/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9165
Epoch 48/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9181
Epoch 49/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9169
Epoch 50/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9098
Epoch 51/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9092
Epoch 52/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9036
Epoch 53/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9027
Epoch 54/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9028
Epoch 55/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8975
Epoch 56/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8967
Epoch 57/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8925
Epoch 58/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8918
Epoch 59/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8881
Epoch 60/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8858
Epoch 61/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8850
Epoch 62/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8849
Epoch 63/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8811
Epoch 64/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8781
Epoch 65/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8762
Epoch 66/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8748
Epoch 67/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8714
Epoch 68/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8720
Epoch 69/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8673
Epoch 70/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8665
Epoch 71/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8659
Epoch 72/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8609
Epoch 73/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8584
Epoch 74/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8592
Epoch 75/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.8560

In [82]:
model.get_weights()

[array([[0.33437192, 0.33437192],
        [0.4309381 , 0.4309381 ]], dtype=float32),
 array([0.28996304, 0.28996304], dtype=float32),
 array([[0.39939436],
        [0.39939436]], dtype=float32),
 array([0.21392854], dtype=float32)]