In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
import kagglehub
path = kagglehub.dataset_download("uciml/breast-cancer-wisconsin-data")

Using Colab cache for faster access to the 'breast-cancer-wisconsin-data' dataset.

In [3]:
df = pd.read_csv(path + "/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

# Preprocessing on features.

In [5]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [6]:
df.sample(5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
387,B,13.88,16.16,88.37,596.6,0.07026,0.04831,0.02045,0.008507,0.1607,...,15.51,19.97,99.66,745.3,0.08484,0.12330,0.1091,0.04537,0.2542,0.06623
392,M,15.49,19.97,102.40,744.7,0.11600,0.15620,0.18910,0.091130,0.1929,...,21.20,29.41,142.10,1359.0,0.16810,0.39130,0.5553,0.21210,0.3187,0.10190
365,M,20.44,21.78,133.80,1293.0,0.09150,0.11310,0.09799,0.077850,0.1618,...,24.31,26.37,161.20,1780.0,0.13270,0.23760,0.2702,0.17650,0.2609,0.06735
102,B,12.18,20.52,77.22,458.7,0.08013,0.04038,0.02383,0.017700,0.1739,...,13.34,32.84,84.58,547.8,0.11230,0.08862,0.1145,0.07431,0.2694,0.06878
408,M,17.99,20.66,117.80,991.7,0.10360,0.13040,0.12010,0.088240,0.1992,...,21.08,25.41,138.10,1349.0,0.14820,0.37350,0.3301,0.19740,0.3060,0.08503

In [7]:
df.shape

(569, 31)

In [8]:
X = df.drop(['diagnosis'], axis=1)
y = df['diagnosis']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15)

In [10]:
X_train.shape, y_train.shape

((455, 30), (455,))

In [11]:
sd = StandardScaler()
X_train = sd.fit_transform(X_train)
X_test = sd.transform(X_test)

In [12]:
X_train

array([[ 1.44126673, -0.26826271,  1.39573983, ...,  1.67055899,
         1.05660813, -0.36171865],
       [-0.67952428,  1.21864604, -0.63294327, ...,  0.23152728,
        -0.18338545,  0.8745434 ],
       [ 0.36574237,  0.15690769,  0.40594363, ...,  1.47086285,
         0.42164318,  0.99913234],
       ...,
       [ 0.96814604,  0.33980221,  1.00461069, ...,  0.54707766,
        -0.71908789, -0.38946801],
       [-0.24216271, -1.3276258 , -0.25698036, ..., -0.36405502,
        -0.28895035, -0.62618699],
       [-0.69602849,  2.37064402, -0.69280997, ..., -0.72045927,
        -0.05576223, -0.68281832]])

In [13]:
y_train

282    M
537    B
392    M
98     B
275    B
      ..
85     M
199    M
156    M
384    B
456    B
Name: diagnosis, Length: 455, dtype: object

In [14]:
lb = LabelEncoder()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [15]:
y_train.shape

(455,)

# Numpy to Tensor transformation.

In [16]:
import torch

X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

# Neural Network defination.

In [17]:
class myNN:
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  # function to calculate loss (binary cross-entropy loss)
  def loss(self, prediction, target):
    epsilon = 1e-7  # to prevent log(0)
    y_pred = torch.clamp(prediction, epsilon, 1 - epsilon)
    loss = -(target * torch.log(y_pred) + (1 - target) * torch.log(1 - y_pred)).mean()
    return loss

## training pipeline.

In [18]:
learningRate = 0.01
epochs = 500

In [19]:
md = myNN(X_train_tensor)

for i in range(epochs):
  # forward pass
  y_pred = md.forward(X_train_tensor)

  # loss calculation
  loss = md.loss(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameter update
  with torch.no_grad():
    md.weights -= learningRate * md.weights.grad
    md.bias -= learningRate * md.bias.grad

  # zero gradients
  md.weights.grad = None
  md.bias.grad = None

  if i % 100 == 0:
    print(f'epchs = {i}, loss = {loss.item()}')

epchs = 0, loss = 3.6836291894794377
epchs = 100, loss = 2.2637290046092358
epchs = 200, loss = 1.0164245785305397
epchs = 300, loss = 0.7805753843123133
epchs = 400, loss = 0.7351139437975697

In [20]:
loss = md.loss(md.forward(X_train_tensor), y_train_tensor)

print(loss.requires_grad)
print(loss.grad_fn)

True
<NegBackward0 object at 0x7957b8822c50>

In [21]:
# model evaluation
with torch.no_grad():
  y_pred = md.forward(X_test_tensor)
  y_pred = np.round(y_pred.numpy()).flatten()

accuracy = (y_pred == y_test_tensor).float().mean()
print(accuracy)

tensor(0.5526)

## New training pipeline.

In [63]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [64]:
import torch.nn as nn

In [65]:
class basic_NN(nn.Module):
  def __init__(self, num_features):
    # define neual network architecture
    super().__init__()    # invoke parent class's constructor
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    output = self.linear(features)
    output = self.sigmoid(output)
    return output

In [66]:
X_train_tensor.shape, y_train_tensor.shape

(torch.Size([455, 30]), torch.Size([455]))

In [67]:
X_train_tensor

tensor([[ 1.4413, -0.2683,  1.3957,  ...,  1.6706,  1.0566, -0.3617],
        [-0.6795,  1.2186, -0.6329,  ...,  0.2315, -0.1834,  0.8745],
        [ 0.3657,  0.1569,  0.4059,  ...,  1.4709,  0.4216,  0.9991],
        ...,
        [ 0.9681,  0.3398,  1.0046,  ...,  0.5471, -0.7191, -0.3895],
        [-0.2422, -1.3276, -0.2570,  ..., -0.3641, -0.2890, -0.6262],
        [-0.6960,  2.3706, -0.6928,  ..., -0.7205, -0.0558, -0.6828]])

In [68]:
# Built in binary cross entropy loss function.
loss_func = nn.BCELoss()

In [69]:
n = X_train_tensor.shape[1]
model = basic_NN(n)

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learningRate)

for i in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculation
  loss = loss_func(y_pred, y_train_tensor.view(-1, 1))

  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # # parameter update
  # with torch.no_grad():
  #   model.linear.weight -= learningRate * model.linear.weight.grad
  #   model.linear.bias -= learningRate * model.linear.bias.grad

  # # zero gradients
  # model.linear.weight.grad = None
  # model.linear.bias.grad = None
  optimizer.step()

  if i % 100 == 0:
    print(f'epchs = {i}, loss = {loss.item()}')

epchs = 0, loss = 0.9421765208244324
epchs = 100, loss = 0.24555978178977966
epchs = 200, loss = 0.17839322984218597
epchs = 300, loss = 0.14925651252269745
epchs = 400, loss = 0.13219577074050903

In [70]:
# model evaluation
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = np.round(y_pred.numpy()).flatten()

accuracy = (y_pred == y_test_tensor).float().mean()
print(accuracy.item())

0.9298245906829834