In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('play_tennis.csv')

In [4]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [5]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [6]:
p_yes = 9 / 14
p_no = 5 / 14

In [7]:
p_yes, p_no

(0.6428571428571429, 0.35714285714285715)

In [8]:
# for outlook
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [ ]:
p_ovr_no = 0
p_rain_no = 2 / 5
p_sunny_no = 3 / 5

p_ovr_yes = 4 / 9
p_rain_yes = 3 / 9
p_sunny_yes = 2 / 9